# -*- coding: utf-8 -*-
"""DonDew_HealthSense.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R4CwWwuw4r7n_eMbC38UQY3BZ_1Dr34x
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/Symptom2Disease.csv")

df.head()

df.shape

df.columns

df['label'].unique()

x = df['text']
y = df['label']

"""Apply TF-IDF"""

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=5000
)

x_vectorized = vectorizer.fit_transform(x)

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x_vectorized, y,
    test_size=0.2,
    random_state=42
)

"""Create the model"""

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

"""Train the Model"""

model.fit(x_train,y_train)

"""Evaluate the Model"""

from sklearn.metrics import accuracy_score

y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)

accuracy

"""Test with own Sentence"""

test_text = ["I have red itchy skin with silvery scales and joint pain"]

test_vector = vectorizer.transform(test_text)

model.predict(test_vector)

"""Show Prediction probabilities"""

model.predict_proba(test_vector)

"""Save the Model and Vectorizer"""

import pickle

with open("disease_model.pkl", "wb") as f:
  pickle.dump(model, f)

with open("tfidf_vectorizer.pkl", "wb") as f:
  pickle.dump(vectorizer, f)